services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      - '.env'
    volumes:
      - ../db-data/:/var/lib/postgresql/data
  back:
    container_name: back
    build: ../back/.
    depends_on:
      - postgres
    ports:
      - 4000:4000
    restart: always
    volumes:
      - ../back/prisma/:/app/prisma
      - ../back/src/:/app/src
  front:
    build: .
    ports:
      - 3000:3000
    container_name: front
    volumes:
      - ./pages/:/app/pages
      - ./public/:/app/public
      - ./components/:/app/components
      - ./styles/:/app/styles
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    container_name: adminer
    
