services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
        # PGDATA: /var/lib/postgresql/data/pgdata
    env_file:
      - './.env'
    ports:
      - 5432:5432
    volumes:
      - ../db-data/:/var/lib/postgresql/data
      - ../init-db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
  back:
    stdin_open: true
    build: ../back/.
    depends_on:
      - postgres
    ports:
      - 4000:4000
    restart: always
  front:
    build: .
    ports:
      - 3000:3000
volumes:
  db-data:
  init-db:

 

    

    