services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      - '.env'
    volumes:
      - ../db-data/:/var/lib/postgresql/data
  back:
    build: ../back/.
    depends_on:
      - postgres
    ports:
      - 4000:4000
    restart: always
    volumes:
      - ../back/prisma/:/app/prisma
      - ../back/src/:/app/src
  front:
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./pages/:/app/pages
      - ./public/:/app/public
      - ./components/:/app/components
      - ./styles/:/app/styles
  # prisma-studio:
  #   container_name: prisma-studio
  #   image: timothyjmiller/prisma-studio:latest
  #   depends_on:
  #     - postgres
  #   restart: unless-stopped
  #   ports:
  #     - 5555:5555
  #   env_file:
  #     - '../back/prisma/.env'
